import { FilterType } from '../schemas/input';

// IP Filter Map - maps colId to filter type
export const ipFilterMap = new Map<string, FilterType | undefined>([
  ['ipSelectionCheckbox', undefined],
  ['action', undefined],
  ['title', 'text'],
  ['rag', 'set'],
  ['executionState', 'set'],
  ['executionOnly', 'set'],
  ['openForTimeEntry', 'set'],
  ['shortId', 'text'],
  ['type', 'set'],
  ['state', 'set'],
  ['benefitsReportingLevel', 'set'],
  ['businessCase', 'text'],
  ['productName', 'text'],
  ['areaProduct', 'text'],
  ['productOwner', 'text'],
  // Financial fields (cost fields for previous, current, next year)
  ['financials.live2024', 'number'],
  ['financials.outlook2024', 'number'],
  ['financials.budget2024', 'number'],
  ['financials.live2025', 'number'],
  ['financials.outlook2025', 'number'],
  ['financials.budget2025', 'number'],
  ['financials.live2026', 'number'],
  ['financials.outlook2026', 'number'],
  ['financials.budget2026', 'number'],
  ['startDate', 'date'],
  ['endDate', 'date'],
  ['owner', 'text'],
  ['coOwners', 'text'],
  ['agreementApprovers', 'text'],
  ['collaborators', 'text'],
  ['cto', 'text'],
  ['cbt', 'text'],
  ['sponsor', 'text'],
  ['primaryFbm', 'text'],
  ['additionalFbms', 'text'],
  ['governanceStructure', 'text'],
  ['salesLead', 'text'],
  ['quantLead', 'text'],
  ['uxLead', 'text'],
  ['productLead', 'text'],
  ['operationsLead', 'text'],
  ['technologyLead', 'text'],
  ['reportingLead', 'text'],
  ['programManager', 'text'],
  ['l1SponsorOrganization', 'set'],
  ['l2SponsorOrganization', 'set'],
  ['l3SponsorOrganization', 'set'],
  ['l1OwningOrganization', 'set'],
  ['l2OwningOrganization', 'set'],
  ['l3OwningOrganization', 'set'],
  ['inPlan', 'set'],
  ['labels', 'text'],
  ['milestoneDeliveryTeams', 'set'],
  ['openCreationDate', 'date'],
  ['openCreatorName', 'text'],
  ['overview', 'text'],
  ['benefitsSummary', 'text'],
  ['regionalImpact', 'set'],
  ['lastApprovedDate', 'date'],
  ['externalId', 'text'],
  ['lumaPhase', 'set'],
]);

// Milestone Filter Map - maps colId to filter type
export const milestoneFilterMap = new Map<string, FilterType | undefined>([
  ['ipSelectionCheckbox', undefined], // checkboxColumnSSRM has filter: false, but treated as undefined since no filter
  ['action', undefined], // actionColumnSSRM has filter: false, but treated as undefined since no filter
  ['shortId', 'text'],
  ['name', 'text'],
  ['proposalType', undefined],
  ['rag', undefined], // Special renderer, no specific filter mentioned
  ['state', undefined], // Special renderer, no specific filter mentioned
  ['overview', 'text'],
  ['keyResult', 'text'],
  ['status', 'text'],
  ['completionDate', 'date'],
  ['statusUpdateDate', 'date'],
  ['statusUpdatedBy', 'text'],
  ['pathToGreen', 'text'],
  ['targetDateToGreen', 'date'],
  ['causeCode', undefined],
  ['delayExplanation', 'text'],
  ['reportingLevel', undefined],
  ['jiraUrl', 'text'],
  ['startDate', 'date'],
  ['endDate', 'date'],
  ['createDate', 'date'],
  ['originalEndDate', 'date'],
  ['previousEndDate', 'date'],
  ['reasonForEndDateChange', undefined],
  ['owner', 'text'],
  ['proposalName', 'text'],
  ['proposalShortId', 'text'],
  ['proposalExecutionState', undefined],
  ['businessCaseActive', undefined],
  ['sponsors', 'text'],
  ['l1OwningOrganization', undefined],
  ['l2OwningOrganization', undefined],
  ['l3OwningOrganization', undefined],
  ['labels', 'text'],
  ['proposalState', undefined], // Special renderer, no specific filter mentioned
  ['businessCaseId', undefined],
  ['businessCaseName', undefined],
  ['cto', 'text'],
  ['externalId', 'text'],
  ['externalSourceId', undefined],
  ['cfo', 'text'],
  ['l1SponsorOrganization', undefined],
  ['l2SponsorOrganization', undefined],
  ['l3SponsorOrganization', undefined],
  ['externallyUpdatedOn', 'date'],
  ['externallyUpdatedBy', 'text'],
  ['clientImpact', undefined],
  ['impactedCountries', 'text'],
  ['impactedRegion', 'text'],
  ['impactedLegalEntities', 'text'],
  ['previousProposalName', 'text'],
  ['deliveryTeam', undefined],
  ['governanceStructure', undefined],
  ['productLead', 'text'],
  ['operationsLead', 'text'],
  ['techLead', 'text'],
  ['reportingLead', 'text'],
]);

// Helper function to get filter type for IP columns
export const getIpColumnFilter = (colId: string): FilterType | undefined => {
  return ipFilterMap.get(colId);
};

// Helper function to get filter type for Milestone columns  
export const getMilestoneColumnFilter = (colId: string): FilterType | undefined => {
  return milestoneFilterMap.get(colId);
};